// React/src/commons/Modal.tsx
import "../styles/modal.css";
import Button from "./Button";

interface ModalProps {
  content: string;
  closeModal: () => void;
  onConfirm: () => void;
}

export default function Modal ({content, closeModal, onConfirm}: ModalProps) {
  return (
    <div className="overlay">
      <dialog open className="modal-container">
        <p>{content}</p>
        <div className="btn-box">
          <Button onClick={closeModal} color="secondary">취소</Button>
          <Button onClick={onConfirm} color="destructive">확인</Button>
        </div>
      </dialog>
    </div>
  )
}

// Svelte/src/commons/Modal.svelte
<script lang="ts">
	import Button from './Button.svelte';

	export let content: string;
	export let closeModal: () => void;
</script>

<div class="overlay">
	<dialog open class="modal-container">
		<p>{content}</p>
		<div>
			<Button content="취소" onClick={closeModal} color="Secondary" />
			<Button content="확인" onClick={closeModal} color="Destructive" />
		</div>
	</dialog>
</div>

<style>
	.overlay {
		position: fixed;
		inset: 0;
		width: 100%;
		height: 100%;
		background-color: rgba(0, 0, 0, 0.3);
	}

	.modal-container {
		position: absolute;
		width: 200px;
		height: 120px;
		left: 50%;
		top: 50%;
		margin: 0;
		transform: translate(-50%, -50%);

		display: flex;
		align-items: center;
		justify-content: center;
		flex-direction: column;

		gap: 20px;
		border-radius: 10px;
		border: none;
		box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
	}
</style>
