// Svelte/src/components/TodoItem.svelte
<script lang="ts">
	import Button from '../commons/Button.svelte';
	import Modal from '../commons/Modal.svelte';

	export let item: {
		id: number;
		content: string;
		completed: boolean;
	};

	let isOpen: Boolean = false;

	function openModal() {
		isOpen = true;
	}

	function closeModal() {
		isOpen = false;
	}
</script>

<div class="todo-container">
	<div>
		<label>
			<input type="checkbox" bind:checked={item.completed} on:click={() => console.log('완료')} />
			<span>{item.content}</span>
		</label>
	</div>

	<div>
		<Button content="수정" onClick={() => {}} color="Secondary" />
		<Button content="삭제" onClick={openModal} color="Destructive" />
	</div>

	{#if isOpen}
		<Modal content="모달을 닫으시겠습니까?" {closeModal} />
	{/if}
</div>

<style>
	.todo-container {
		display: flex;
		align-items: center;
		justify-content: center;
		flex-direction: row;

		padding: 10px 0;
		gap: 40px;
	}
</style>

// React/src/components/TodoItem.tsx
import "../styles/todoItem.css";
import Button from "../commons/Button";
import { TodoType } from "../types/todo";
import Modal from "../commons/Modal";
import { deleteTodo } from "../apis/deleteTodo";
import useModal from "../hooks/useModal";

interface TodoItemProps {
  item: TodoType;
}

export default function TodoItem({item}: TodoItemProps) {
  const { isOpen, openModal, closeModal } = useModal();

  const handleDelete = () => {
    deleteTodo(item.id);
    window.location.reload();
  }

  return (
    <div className="todo-container">
      <label>
        <input type="checkbox" checked={item.completed} onChange={() => {}}/>
        <span>{item.content}</span> 
      </label>

      <div className="btn-container">
        <Button onClick={() => {}} color="secondary">수정</Button>
        <Button onClick={openModal} color="destructive">삭제</Button>
      </div>


      {isOpen && <Modal content="할 일을 삭제하시겠습니까?" closeModal={closeModal} onConfirm={handleDelete} />}
    </div>
  )
}
